mitctl_vmi: process-info.c parse.c mitctl_vmi.h rpc_vmi.c
	gcc process-info.c  parse.c  rpc_vmi.c  -o mitctl_vmi -L	/usr/local/lib 	-lvirt -lm -lvmi -lxenctrl -lxenstore -ldisasm  -I/usr/local/mysql/include/ -L/usr/local/mysql/lib/  -lmysqlclient




